# Generated by Django 2.2.7 on 2023-05-28 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_mymodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyModel',
            new_name='Permission',
        ),
    ]
