# Generated by Django 2.2.7 on 2023-05-28 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20230528_1510'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
